name = "danmu-api"
main = "danmu_api/worker.js"
compatibility_date = "2025-09-13"
keep_vars = true
compatibility_flags = ["nodejs_compat"]

[vars]
TOKEN = "87654321"
SOURCE_ORDER = "360,tencent,youku"
PLATFORM_ORDER = "qq,youku,qiyi"
SEARCH_CACHE_MINUTES = "5"
DANMU_OUTPUT_FORMAT = "json"
